name: Make Windows Bundle

on:
  # Only trigger on release creation
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Run CMake
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" ..

    - name: Build with CMake
      run: |
        cd build
        cmake --build --config Release .
        copy bin\\RELEASE\\WinHippoAutoProxy.exe ..\\
        copy bin\\RELEASE\\socks5udphooker.dll ..\\
        copy C:\\Windows\\System32\\msvcp140.dll ..\\
        copy C:\\Windows\\System32\\vcruntime140.dll ..\\
        copy C:\\Windows\\System32\\vcruntime140_1.dll ..\\

    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: WinHippoAutoProxy-${{ github.sha }}
        path: |
          WinHippoAutoProxy.exe
          *.dll
          README.md
          LICENSE
